# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screensUI/btns_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Buttons(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 150)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 150))
        self.frame.setStyleSheet("background-color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.login = QtWidgets.QPushButton(self.frame)
        self.login.setGeometry(QtCore.QRect(345, 25, 115, 30))
        self.login.setStyleSheet("QPushButton{\n"
"background-color:rgb(42, 22, 111);\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(5, 122, 192);\n"
"color:white;\n"
"}")
        self.login.setObjectName("login")
        self.reg_btn = QtWidgets.QPushButton(self.frame)
        self.reg_btn.setGeometry(QtCore.QRect(345, 75, 115, 30))
        self.reg_btn.setStyleSheet("QPushButton{\n"
"background-color:rgb(42, 22, 111);\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(5, 122, 192);\n"
"color:white;\n"
"}")
        self.reg_btn.setObjectName("reg_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login.setText(_translate("Form", "Login"))
        self.reg_btn.setText(_translate("Form", "Register"))
