# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screensUI/loading_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoadingWin(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 150)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 150))
        self.frame.setStyleSheet("background-color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bar_text = QtWidgets.QLabel(self.frame)
        self.bar_text.setGeometry(QtCore.QRect(156, 29, 441, 41))
        self.bar_text.setAlignment(QtCore.Qt.AlignCenter)
        self.bar_text.setWordWrap(True)
        self.bar_text.setObjectName("bar_text")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(170, 90, 441, 16))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.bar_text.setText(_translate("Form", "Loading..."))
