# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SNGPL/screensUI/register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RegisterWin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setAcceptDrops(False)
        self.frame.setStyleSheet("background-color:rgb(59, 248, 41);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(250, 0, 550, 600))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color:rgb(48, 72, 188);\n"
"border-top-left-radius:250px;\n"
"border-bottom-left-radius:150px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(100, 180, 175, 50))
        self.frame_3.setStyleSheet("background-color:white;\n"
"border-radius:25px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 5, 100, 10))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 125, 20))
        self.lineEdit.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.lineEdit.setObjectName("lineEdit")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(300, 180, 175, 50))
        self.frame_4.setStyleSheet("background-color:white;\n"
"border-radius:25px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(20, 5, 100, 13))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 20, 125, 20))
        self.lineEdit_2.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(100, 260, 375, 50))
        self.frame_5.setStyleSheet("background-color:white;\n"
"border-radius:25px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(20, 5, 100, 13))
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 20, 325, 20))
        self.lineEdit_3.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(100, 340, 175, 50))
        self.frame_6.setStyleSheet("background-color:white;\n"
"border-radius:25px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(20, 5, 100, 13))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 20, 125, 20))
        self.lineEdit_4.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setGeometry(QtCore.QRect(300, 340, 175, 50))
        self.frame_7.setStyleSheet("background-color:white;\n"
"border-radius:25px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(20, 5, 100, 13))
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 20, 125, 20))
        self.lineEdit_5.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(210, 475, 150, 25))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color:rgb(63, 158, 183);\n"
"color:white;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(107, 198, 182);\n"
"color:white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(210, 100, 150, 30))
        self.frame_8.setStyleSheet("background-color:rgb(132, 204, 197);\n"
"border-radius:15px;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setGeometry(QtCore.QRect(25, 5, 100, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setGeometry(QtCore.QRect(100, 420, 375, 30))
        self.frame_9.setStyleSheet("background-color:rgb(132, 204, 197);\n"
"border-radius:15px;\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setGeometry(QtCore.QRect(20, 7, 60, 15))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.radioButton = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton.setGeometry(QtCore.QRect(90, 7, 80, 15))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_2.setGeometry(QtCore.QRect(270, 7, 82, 15))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_9)
        self.radioButton_3.setGeometry(QtCore.QRect(180, 7, 80, 15))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 510, 150, 25))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color:rgb(63, 158, 183);\n"
"color:white;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(107, 198, 182);\n"
"color:white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(75, 250, 100, 100))
        self.label.setStyleSheet("image:url(:/Images/sngpl_logo.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Last Name"))
        self.label_5.setText(_translate("MainWindow", "E-mail"))
        self.label_6.setText(_translate("MainWindow", "Password"))
        self.label_7.setText(_translate("MainWindow", "Confirm Password"))
        self.pushButton.setText(_translate("MainWindow", "REGISTER"))
        self.label_2.setText(_translate("MainWindow", "Register Yourself"))
        self.label_8.setText(_translate("MainWindow", "Register as"))
        self.radioButton.setText(_translate("MainWindow", "Admin"))
        self.radioButton_2.setText(_translate("MainWindow", "Calibrator"))
        self.radioButton_3.setText(_translate("MainWindow", "Operator"))
        self.pushButton_2.setText(_translate("MainWindow", "LOGIN"))
