# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SNGPL/screensUI/sitescreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SiteWin(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frame.setStyleSheet("background-color:white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 800, 200))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 150, 200))
        self.frame_4.setStyleSheet("background-color: rgb(51, 150, 173);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(25, 50, 100, 100))
        self.label.setStyleSheet("image: url(:/Images/sngpl_logo.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(150, 0, 650, 200))
        self.frame_5.setStyleSheet("background-color:rgb(4, 107, 183);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(5, 15, 150, 50))
        self.frame_6.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_2.setObjectName("label_2")
        self.station_name = QtWidgets.QLineEdit(self.frame_6)
        self.station_name.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.station_name.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.station_name.setObjectName("station_name")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(5, 135, 150, 50))
        self.frame_7.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_3 = QtWidgets.QLabel(self.frame_7)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_3.setObjectName("label_3")
        self.station_status = QtWidgets.QLineEdit(self.frame_7)
        self.station_status.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.station_status.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.station_status.setObjectName("station_status")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setGeometry(QtCore.QRect(5, 75, 150, 50))
        self.frame_8.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_4.setObjectName("label_4")
        self.last_updated_time = QtWidgets.QLineEdit(self.frame_8)
        self.last_updated_time.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.last_updated_time.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.last_updated_time.setObjectName("last_updated_time")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setGeometry(QtCore.QRect(160, 15, 150, 50))
        self.frame_9.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_5 = QtWidgets.QLabel(self.frame_9)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_5.setObjectName("label_5")
        self.station_site = QtWidgets.QLineEdit(self.frame_9)
        self.station_site.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.station_site.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.station_site.setObjectName("station_site")
        self.frame_10 = QtWidgets.QFrame(self.frame_5)
        self.frame_10.setGeometry(QtCore.QRect(160, 135, 150, 50))
        self.frame_10.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_6 = QtWidgets.QLabel(self.frame_10)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_6.setObjectName("label_6")
        self.station_alrm = QtWidgets.QLineEdit(self.frame_10)
        self.station_alrm.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.station_alrm.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.station_alrm.setObjectName("station_alrm")
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setGeometry(QtCore.QRect(160, 75, 150, 50))
        self.frame_11.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_7.setObjectName("label_7")
        self.start_date_time = QtWidgets.QDateTimeEdit(self.frame_11)
        self.start_date_time.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.start_date_time.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.start_date_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.start_date_time.setObjectName("start_date_time")
        self.frame_12 = QtWidgets.QFrame(self.frame_5)
        self.frame_12.setGeometry(QtCore.QRect(315, 15, 150, 50))
        self.frame_12.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_8 = QtWidgets.QLabel(self.frame_12)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_8.setObjectName("label_8")
        self.station_id = QtWidgets.QLineEdit(self.frame_12)
        self.station_id.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.station_id.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.station_id.setObjectName("station_id")
        self.frame_13 = QtWidgets.QFrame(self.frame_5)
        self.frame_13.setGeometry(QtCore.QRect(315, 75, 150, 50))
        self.frame_13.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_9.setObjectName("label_9")
        self.end_date_time = QtWidgets.QDateTimeEdit(self.frame_13)
        self.end_date_time.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.end_date_time.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.end_date_time.setWrapping(False)
        self.end_date_time.setFrame(True)
        self.end_date_time.setProperty("showGroupSeparator", False)
        self.end_date_time.setDate(QtCore.QDate(2022, 1, 1))
        self.end_date_time.setTime(QtCore.QTime(23, 59, 59))
        self.end_date_time.setObjectName("end_date_time")
        self.frame_14 = QtWidgets.QFrame(self.frame_5)
        self.frame_14.setGeometry(QtCore.QRect(315, 135, 150, 50))
        self.frame_14.setStyleSheet("background-color:rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 75, 15))
        self.label_10.setObjectName("label_10")
        self.station_pressure = QtWidgets.QLineEdit(self.frame_14)
        self.station_pressure.setGeometry(QtCore.QRect(10, 25, 125, 15))
        self.station_pressure.setStyleSheet("border:0px;\n"
"border-bottom:2px solid black;")
        self.station_pressure.setObjectName("station_pressure")
        self.frame_15 = QtWidgets.QFrame(self.frame_5)
        self.frame_15.setGeometry(QtCore.QRect(475, 15, 70, 170))
        self.frame_15.setStyleSheet("background-color: rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.update_pressure = QtWidgets.QPushButton(self.frame_15)
        self.update_pressure.setGeometry(QtCore.QRect(5, 30, 60, 20))
        self.update_pressure.setStyleSheet("QPushButton{\n"
"background-color:rgb(4, 107, 183);\n"
"color:white;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(105, 196, 186);\n"
"color:white;\n"
"}\n"
"")
        self.update_pressure.setObjectName("update_pressure")
        self.read_pressure = QtWidgets.QPushButton(self.frame_15)
        self.read_pressure.setGeometry(QtCore.QRect(5, 75, 60, 20))
        self.read_pressure.setStyleSheet("QPushButton{\n"
"background-color:rgb(4, 107, 183);\n"
"color:white;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(105, 196, 186);\n"
"color:white;\n"
"}\n"
"")
        self.read_pressure.setObjectName("read_pressure")
        self.plot_graph = QtWidgets.QPushButton(self.frame_15)
        self.plot_graph.setGeometry(QtCore.QRect(5, 120, 60, 20))
        self.plot_graph.setStyleSheet("QPushButton{\n"
"background-color:rgb(4, 107, 183);\n"
"color:white;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(105, 196, 186);\n"
"color:white;\n"
"}\n"
"")
        self.plot_graph.setObjectName("plot_graph")
        self.frame_16 = QtWidgets.QFrame(self.frame_5)
        self.frame_16.setGeometry(QtCore.QRect(555, 15, 85, 170))
        self.frame_16.setStyleSheet("background-color: rgb(78, 174, 185);\n"
"border-radius:25px;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_11 = QtWidgets.QLabel(self.frame_16)
        self.label_11.setGeometry(QtCore.QRect(5, 30, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_16)
        self.label_12.setGeometry(QtCore.QRect(5, 90, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.lcdinpressure = QtWidgets.QLCDNumber(self.frame_16)
        self.lcdinpressure.setGeometry(QtCore.QRect(10, 60, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(False)
        self.lcdinpressure.setFont(font)
        self.lcdinpressure.setAutoFillBackground(False)
        self.lcdinpressure.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdinpressure.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdinpressure.setProperty("intValue", 0)
        self.lcdinpressure.setObjectName("lcdinpressure")
        self.lcdoutpressure = QtWidgets.QLCDNumber(self.frame_16)
        self.lcdoutpressure.setGeometry(QtCore.QRect(10, 120, 65, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdoutpressure.setFont(font)
        self.lcdoutpressure.setProperty("intValue", 0)
        self.lcdoutpressure.setObjectName("lcdoutpressure")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 200, 800, 400))
        self.frame_3.setStyleSheet("background-color: rgb(106, 201, 189);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, 39, 801, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_17 = QtWidgets.QFrame(self.frame_3)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 800, 40))
        self.frame_17.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.station_name.setPlaceholderText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Status"))
        self.station_status.setPlaceholderText(_translate("MainWindow", "Status"))
        self.label_4.setText(_translate("MainWindow", "Last Updated"))
        self.last_updated_time.setPlaceholderText(_translate("MainWindow", "Last updated"))
        self.label_5.setText(_translate("MainWindow", "Site"))
        self.station_site.setPlaceholderText(_translate("MainWindow", "Site"))
        self.label_6.setText(_translate("MainWindow", "Alarm"))
        self.station_alrm.setPlaceholderText(_translate("MainWindow", "Alarm"))
        self.label_7.setText(_translate("MainWindow", "Start Time"))
        self.start_date_time.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd hh:mm:ss"))
        self.label_8.setText(_translate("MainWindow", "TBS"))
        self.station_id.setPlaceholderText(_translate("MainWindow", "TBS id"))
        self.label_9.setText(_translate("MainWindow", "End Time"))
        self.end_date_time.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd hh:mm:ss"))
        self.label_10.setText(_translate("MainWindow", "Pressure"))
        self.station_pressure.setPlaceholderText(_translate("MainWindow", "Pressure"))
        self.update_pressure.setText(_translate("MainWindow", "Update"))
        self.read_pressure.setText(_translate("MainWindow", "Read"))
        self.plot_graph.setText(_translate("MainWindow", "Plot"))
        self.label_11.setText(_translate("MainWindow", "In Pressure"))
        self.label_12.setText(_translate("MainWindow", "Out Pressure"))
